apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: ecommerce-etl
  namespace: default
spec:
  type: Java
  mode: cluster
  image: spark-ecommerce-etl:1.0
  imagePullPolicy: IfNotPresent
  mainClass: com.example.etl.EcommerceETL
  mainApplicationFile: local:///opt/spark/app/app.jar
  sparkVersion: "3.5.0"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: "1g"
  executor:
    instances: 2
    cores: 1
    memory: "1g"
